<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'senvora',
  'creator_name' => 'senvora',
  'creation_date' => '2025-08-19',
  'rev_no' => 'R0',
  'remarks' => 'Edit Url paths based on your local file locations | Edit Timezone based on your file | Edit culture info based on your files',
  'timezone' => 'Asia/Kolkata',
  'culture' => 'en',
  'max_day' => '3',
  'rating_system' => 'EN',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'pastdayremover' => 'on',
  'compressionOption' => '1',
  'url1' => 'https://github.com/senvora/tvguide/raw/refs/heads/main/epg/senvora.xml.gz',
  'requestOption1' => '1',
  'show' => '(<programme.*?<\\/programme>)||#include#channel="##channel##">',
  'start' => 'start="(\\d+)\\s',
  'start_format' => 'YmdHis',
  'stop' => 'stop="(\\d+)\\s',
  'stop_format' => 'YmdHis',
  'title' => '<title.*?>(.*?)<\\/',
  'desc' => '<desc.*?>(.*?)<\\/',
  'category' => '<category.*?>(.*?)<\\/',
  'showicon' => '<icon src="(.*?)"',
  'season' => '">S(\\d+)',
  'episode' => '">(?:S\\d+\\s)?E(\\d+)',
  'episode_total' => '">(?:S\\d+\\s)?E\\d+\\/(\\d+)',
  'channel_logo' => '||#add###cclogo##',
  'actor' => '<actor.*?>(.*?)<\\/',
  'director' => '<director>(.*?)<\\/',
  'rating' => '<rating.*?<value>(.*?)<\\/',
  'ccurl1' => 'https://github.com/senvora/tvguide/raw/refs/heads/main/epg/senvora.xml.gz',
  'ccrequestOption1' => '1',
  'ccchannel_block' => '<channel id.*?<\\/channel>',
  'ccchannel_id' => 'id="(.*?)"',
  'ccchannel_name' => '<display-name.*?>(.*?)<\\/',
  'ccchannel_logo' => '<icon src="(.*?)"',
);
?>